# Generated by Django 3.2.3 on 2021-05-30 16:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('abstract', models.CharField(blank=True, max_length=10000)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('tokens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=1000), null=True, size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=1000), null=True, size=None)),
                ('doi', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
