# Generated by Django 3.2.3 on 2021-06-01 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='abstract',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='doi',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=1000), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='document',
            name='tag',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='document',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=10000), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
