# Generated by Django 3.2.3 on 2021-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210601_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
