# Generated by Django 3.2.3 on 2021-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20210608_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='doc_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
