# Generated by Django 3.2.3 on 2021-06-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_tag_doc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='doc_id',
        ),
    ]
