# Generated by Django 3.2.3 on 2021-06-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_remove_tag_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
